(()=>{
'use strict';
const te=new TextEncoder();
const escXml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const colName=n=>{let s='';while(n>0){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s};
const le16=n=>new Uint8Array([n&255,(n>>>8)&255]);
const le32=n=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);
const cat=parts=>{let len=0;for(const p of parts)len+=p.length;const out=new Uint8Array(len);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out};
let crcTable=null;function crc32(bytes){if(!crcTable){crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}}let c=0xFFFFFFFF;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xFFFFFFFF)>>>0}
function zipStore(files){const locals=[],centrals=[];let offset=0;for(const f of files){const name=te.encode(f.name),data=te.encode(f.data),crc=crc32(data);const local=cat([le32(0x04034b50),le16(20),le16(0),le16(0),le16(0),le16(0),le32(crc),le32(data.length),le32(data.length),le16(name.length),le16(0),name,data]);locals.push(local);const central=cat([le32(0x02014b50),le16(20),le16(20),le16(0),le16(0),le16(0),le16(0),le32(crc),le32(data.length),le32(data.length),le16(name.length),le16(0),le16(0),le16(0),le16(0),le32(0),le32(offset),name]);centrals.push(central);offset+=local.length}const centralStart=offset,centralData=cat(centrals),localData=cat(locals);const end=cat([le32(0x06054b50),le16(0),le16(0),le16(files.length),le16(files.length),le32(centralData.length),le32(centralStart),le16(0)]);return new Blob([localData,centralData,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function saveBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200)}

function toXlsx(name,rows,sheet='Datos'){
 rows=Array.isArray(rows)?rows:[];const keys=rows.length?Object.keys(rows[0]):['Sin datos'];
 const cell=(v,r,c,style=0)=>{const ref=colName(c)+r,st=style?` s="${style}"`:'';if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}"${st}><v>${v}</v></c>`;return `<c r="${ref}" t="inlineStr"${st}><is><t>${escXml(v)}</t></is></c>`};
 let sheetRows=`<row r="1" ht="24" customHeight="1">${keys.map((k,i)=>cell(String(k).replaceAll('_',' ').toUpperCase(),1,i+1,1)).join('')}</row>`;
 rows.forEach((row,ri)=>{const r=ri+2;sheetRows+=`<row r="${r}">${keys.map((k,i)=>cell(row[k],r,i+1,0)).join('')}</row>`});
 const widths=keys.map((k,i)=>{const max=Math.min(42,Math.max(12,String(k).length+3,...rows.slice(0,200).map(r=>String(r[k]??'').length+2)));return `<col min="${i+1}" max="${i+1}" width="${max}" customWidth="1"/>`}).join('');
 const files=[
 {name:'[Content_Types].xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`},
 {name:'_rels/.rels',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`},
 {name:'xl/workbook.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${escXml(sheet)}" sheetId="1" r:id="rId1"/></sheets></workbook>`},
 {name:'xl/_rels/workbook.xml.rels',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`},
 {name:'xl/styles.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Aptos Display"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF14243A"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border/><border><bottom style="thin"><color rgb="FFD9E2EC"/></bottom></border></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf xfId="0" fontId="0" fillId="0" borderId="1" applyBorder="1"/><xf xfId="0" fontId="1" fillId="2" borderId="0" applyFont="1" applyFill="1"><alignment vertical="center"/></xf></cellXfs></styleSheet>`},
 {name:'xl/worksheets/sheet1.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols>${widths}</cols><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>${sheetRows}</sheetData><autoFilter ref="A1:${colName(keys.length)}${Math.max(1,rows.length+1)}"/></worksheet>`}
 ];saveBlob(zipStore(files),name)
}

function ascii(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
const pdfText=(x,y,size,text,font='F1',rgb='0.08 0.14 0.23')=>`BT /${font} ${size} Tf ${rgb} rg ${x} ${y} Td (${ascii(text)}) Tj ET\n`;
const pdfRect=(x,y,w,h,rgb='0.96 0.97 0.99',stroke='')=>`${rgb} rg ${x} ${y} ${w} ${h} re f\n${stroke?`${stroke} RG ${x} ${y} ${w} ${h} re S\n`:''}`;
function wrapText(v,max=38){const s=String(v??'');if(!s)return [''];const words=s.split(/\s+/),lines=[];let line='';for(const w of words){const next=line?line+' '+w:w;if(next.length>max&&line){lines.push(line);line=w}else line=next}if(line)lines.push(line);return lines.slice(0,5)}
function toPdf(name,title,rows,subtitle=''){
 rows=Array.isArray(rows)?rows:[];const pages=[],W=595,H=842,margin=34,contentW=W-margin*2;
 const header=(page,total)=>{let c='';c+=pdfRect(0,H-112,W,112,'0.055 0.105 0.18');c+=pdfRect(margin,H-70,34,34,'0.08 0.41 0.82');c+=pdfText(margin+11,H-59,15,'E','F2','1 1 1');c+=pdfText(margin+47,H-46,17,'E-FLEET','F2','1 1 1');c+=pdfText(margin+47,H-63,8,'MANTENIMIENTO INTELIGENTE','F1','0.72 0.80 0.90');c+=pdfText(margin,H-96,13,title,'F2','1 1 1');if(subtitle)c+=pdfText(margin,H-106,7,subtitle,'F1','0.75 0.82 0.91');c+=pdfText(W-98,H-24,7,`Pagina ${page}/${total}`,'F1','0.75 0.82 0.91');return c};
 const footer=()=>pdfText(margin,20,6,`Emitido ${new Date().toLocaleString('es-CL')} · E-Fleet Mantenimiento Inteligente`,'F1','0.42 0.49 0.59');
 if(rows.length===1&&Object.keys(rows[0]).length>6){
   const entries=Object.entries(rows[0]);let chunks=[];for(let i=0;i<entries.length;i+=10)chunks.push(entries.slice(i,i+10));
   chunks.forEach(chunk=>{let c='',y=H-142;c+=pdfRect(margin,y-42,contentW,42,'0.95 0.97 1','0.84 0.89 0.95');c+=pdfText(margin+14,y-17,8,'RESUMEN DE ORDEN / INFORME','F2','0.08 0.36 0.66');c+=pdfText(margin+14,y-32,7,`${entries.length} campos tecnicos registrados`,'F1','0.38 0.46 0.57');y-=60;for(const [k,v] of chunk){const lines=wrapText(v,62),h=Math.max(42,22+lines.length*9);c+=pdfRect(margin,y-h,contentW,h,'0.985 0.99 1','0.90 0.93 0.96');c+=pdfText(margin+12,y-16,7,String(k).replaceAll('_',' ').toUpperCase(),'F2','0.36 0.45 0.57');lines.forEach((ln,i)=>c+=pdfText(margin+12,y-30-i*9,8,ln,'F1','0.08 0.14 0.23'));y-=h+7}pages.push(c)});
 }else{
   const keys=rows.length?Object.keys(rows[0]).slice(0,6):['Sin datos'];const colW=contentW/keys.length,rowsPerPage=24;for(let start=0;start<Math.max(rows.length,1);start+=rowsPerPage){let c='',y=H-142;c+=pdfRect(margin,y-36,contentW,36,'0.95 0.97 1','0.84 0.89 0.95');c+=pdfText(margin+12,y-15,8,'RESUMEN EJECUTIVO','F2','0.08 0.36 0.66');c+=pdfText(margin+12,y-28,7,`${rows.length} registro(s) · ${keys.length} columna(s) visibles`,'F1','0.38 0.46 0.57');y-=54;c+=pdfRect(margin,y-24,contentW,24,'0.08 0.14 0.23');keys.forEach((k,i)=>c+=pdfText(margin+i*colW+5,y-16,6,String(k).replaceAll('_',' ').toUpperCase().slice(0,18),'F2','1 1 1'));y-=24;for(const r of rows.slice(start,start+rowsPerPage)){const vals=keys.map(k=>String(r[k]??'')),lines=vals.map(v=>wrapText(v,Math.max(10,Math.floor(colW/4.7)))),rh=Math.max(25,...lines.map(a=>10+a.length*7));c+=pdfRect(margin,y-rh,contentW,rh,(Math.floor((H-y)/rh)%2)?'0.985 0.99 1':'1 1 1','0.91 0.93 0.96');keys.forEach((k,i)=>lines[i].slice(0,3).forEach((ln,j)=>c+=pdfText(margin+i*colW+5,y-15-j*7,6.4,ln,'F1','0.15 0.20 0.28')));y-=rh;if(y<55)break}pages.push(c)}
 }
 if(!pages.length)pages.push(pdfText(margin,H-160,10,'Sin datos para este informe.','F1'));
 const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';const fontRegular=3+pages.length*2,fontBold=fontRegular+1;objects[2]=`<< /Type /Pages /Kids [${pages.map((_,i)=>`${3+i*2} 0 R`).join(' ')}] /Count ${pages.length} >>`;
 pages.forEach((body,i)=>{const pageId=3+i*2,contentId=4+i*2,stream=header(i+1,pages.length)+body+footer();objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`});
 objects[fontRegular]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';objects[fontBold]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;saveBlob(new Blob([pdf],{type:'application/pdf'}),name)
}
window.EFleetExport={toXlsx,toPdf};
})();
